import {Country} from './country';

export const COUNTRIES: Country[] = [
  {
    // id: 1,
    // name: 'Russia',
    // flag: 'f/f3/Flag_of_Russia.svg',
    // area: 17075200,
    // population: 146989754,
    firstname:'First Name1',
    lastname:'Last Name1',
    emailid:'abc1@gmail.com',
    country:'USA',
    role:'Admin',
    status:'Active'
  },
  {
  //   // id: 2,
  //   // name: 'France',
  //   // flag: 'c/c3/Flag_of_France.svg',
  //   // area: 640679,
  //   // population: 64979548,
  //   firstname:'First Name2',
  //   lastname:'Last Name2',
  //   emailid:'abc2@gmail.com',
  //   country:'IND',
  //   role:'Admin',
  //   status:'Inactive'
  // },
  // {
  //   id: 3,
  //   name: 'Germany',
  //   flag: 'b/ba/Flag_of_Germany.svg',
  //   area: 357114,
  //   population: 82114224,
    firstname:'First Name3',
    lastname:'Last Name3',
    emailid:'abc3@gmail.com',
    country:'USA',
    role:'Clinician',
    status:'Active'
  },
  {
    // id: 4,
    // name: 'Portugal',
    // flag: '5/5c/Flag_of_Portugal.svg',
    // area: 92090,
    // population: 10329506,
    firstname:'First Name4',
    lastname:'Last Name4',
    emailid:'abc4@gmail.com',
    country:'Germany',
    role:'Clinician',
    status:'Active'
  },
  {
    // id: 5,
    // name: 'Canada',
    // flag: 'c/cf/Flag_of_Canada.svg',
    // area: 9976140,
    // population: 36624199,
    firstname:'First Name5',
    lastname:'Last Name5',
    emailid:'abc5@gmail.com',
    country:'Germany',
    role:'Physician',
    status:'Pending'
  },
  {
    // id: 6,
    // name: 'Vietnam',
    // flag: '2/21/Flag_of_Vietnam.svg',
    // area: 331212,
    // population: 95540800,
    firstname:'First Name6',
    lastname:'Last Name6',
    emailid:'abc6@gmail.com',
    country:'USA',
    role:'Staff',
    status:'Inactive'
  },
  {
    // id: 7,
    // name: 'Brazil',
    // flag: '0/05/Flag_of_Brazil.svg',
    // area: 8515767,
    // population: 209288278,
    firstname:'First Name7',
    lastname:'Last Name7',
    emailid:'abc7@gmail.com',
    country:'IND',
    role:'Staff',
    status:'Active'
  },
  {
    // id: 8,
    // name: 'Mexico',
    // flag: 'f/fc/Flag_of_Mexico.svg',
    // area: 1964375,
    // population: 129163276,
    firstname:'First Name8',
    lastname:'Last Name8',
    emailid:'xyz1@gmail.com',
    country:'Australia',
    role:'Admin',
    status:'Pending'
  },
  {
    // id: 9,
    // name: 'United States',
    // flag: 'a/a4/Flag_of_the_United_States.svg',
    // area: 9629091,
    // population: 324459463,
    firstname:'First Name9',
    lastname:'Last Name9',
    emailid:'xyz2@gmail.com',
    country:'Australia',
    role:'Clinician',
    status:'Inactive'
  },
  {
    // id: 10,
    // name: 'India',
    // flag: '4/41/Flag_of_India.svg',
    // area: 3287263,
    // population: 1324171354,
    firstname:'First Name10',
    lastname:'Last Name10',
    emailid:'xyz3@gmail.com',
    country:'Australia',
    role:'Staff',
    status:'Active'
  },
  {
    // id: 11,
    // name: 'Indonesia',
    // flag: '9/9f/Flag_of_Indonesia.svg',
    // area: 1910931,
    // population: 263991379,
    firstname:'First Name11',
    lastname:'Last Name11',
    emailid:'xyz4@gmail.com',
    country:'USA',
    role:'Physician',
    status:'Inactive'
  },
  {
    // id: 12,
    // name: 'Tuvalu',
    // flag: '3/38/Flag_of_Tuvalu.svg',
    // area: 26,
    // population: 11097,
    firstname:'First Name12',
    lastname:'Last Name12',
    emailid:'xyz5@gmail.com',
    country:'IND',
    role:'Staff',
    status:'Pending'
  },
  {
    // id: 13,
    // name: 'China',
    // flag: 'f/fa/Flag_of_the_People%27s_Republic_of_China.svg',
    // area: 9596960,
    // population: 1409517397,
    firstname:'First Name13',
    lastname:'Last Name13',
    emailid:'test@gmail.com',
    country:'IND',
    role:'Admin',
    status:'Inactive'
  }
];
